version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: url-shortener-postgres
    restart: always
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: url-shortener-redis
    restart: always
    ports:
      - "6379:6379"